//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://qyh.webService.est.yonyou.com/", ConfigurationName="ServiceReference1.IQyhWeixinUtilService")]
    public interface IQyhWeixinUtilService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCodeResponse getLocalQyhUserByUserIdOrCode(Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCodeResponse> getLocalQyhUserByUserIdOrCodeAsync(Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.sendMessageToAgentResponse sendMessageToAgent(Laboratory.ServiceReference1.sendMessageToAgent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.sendMessageToAgentResponse> sendMessageToAgentAsync(Laboratory.ServiceReference1.sendMessageToAgent request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getQyhUserByUserIdOrCodeResponse getQyhUserByUserIdOrCode(Laboratory.ServiceReference1.getQyhUserByUserIdOrCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserByUserIdOrCodeResponse> getQyhUserByUserIdOrCodeAsync(Laboratory.ServiceReference1.getQyhUserByUserIdOrCode request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getAllQyhDeptResponse getAllQyhDept(Laboratory.ServiceReference1.getAllQyhDept request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAllQyhDeptResponse> getAllQyhDeptAsync(Laboratory.ServiceReference1.getAllQyhDept request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getQyhUserListByDateResponse getQyhUserListByDate(Laboratory.ServiceReference1.getQyhUserListByDate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserListByDateResponse> getQyhUserListByDateAsync(Laboratory.ServiceReference1.getQyhUserListByDate request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getAllQyhAgentResponse getAllQyhAgent(Laboratory.ServiceReference1.getAllQyhAgent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAllQyhAgentResponse> getAllQyhAgentAsync(Laboratory.ServiceReference1.getAllQyhAgent request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getAccessTokenResponse getAccessToken(Laboratory.ServiceReference1.getAccessToken request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAccessTokenResponse> getAccessTokenAsync(Laboratory.ServiceReference1.getAccessToken request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getQyhUserIdResponse getQyhUserId(Laboratory.ServiceReference1.getQyhUserId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserIdResponse> getQyhUserIdAsync(Laboratory.ServiceReference1.getQyhUserId request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getWeixinPageInitResponse getWeixinPageInit(Laboratory.ServiceReference1.getWeixinPageInit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getWeixinPageInitResponse> getWeixinPageInitAsync(Laboratory.ServiceReference1.getWeixinPageInit request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getJsapiTicketResponse getJsapiTicket(Laboratory.ServiceReference1.getJsapiTicket request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getJsapiTicketResponse> getJsapiTicketAsync(Laboratory.ServiceReference1.getJsapiTicket request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Laboratory.ServiceReference1.getUserIdByMobileResponse getUserIdByMobile(Laboratory.ServiceReference1.getUserIdByMobile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getUserIdByMobileResponse> getUserIdByMobileAsync(Laboratory.ServiceReference1.getUserIdByMobile request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalQyhUserByUserIdOrCode", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getLocalQyhUserByUserIdOrCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getLocalQyhUserByUserIdOrCode() {
        }
        
        public getLocalQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            this.userId = userId;
            this.code = code;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalQyhUserByUserIdOrCodeResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getLocalQyhUserByUserIdOrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getLocalQyhUserByUserIdOrCodeResponse() {
        }
        
        public getLocalQyhUserByUserIdOrCodeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class qyhMessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgtypeField;
        
        private newsMessageVO newsVOField;
        
        private textMessageVO textVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string msgtype {
            get {
                return this.msgtypeField;
            }
            set {
                this.msgtypeField = value;
                this.RaisePropertyChanged("msgtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public newsMessageVO newsVO {
            get {
                return this.newsVOField;
            }
            set {
                this.newsVOField = value;
                this.RaisePropertyChanged("newsVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public textMessageVO textVO {
            get {
                return this.textVOField;
            }
            set {
                this.textVOField = value;
                this.RaisePropertyChanged("textVO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class newsMessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentidField;
        
        private articleVO[] articlesField;
        
        private string msgtypeField;
        
        private string topartyField;
        
        private string totagField;
        
        private string touserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agentid {
            get {
                return this.agentidField;
            }
            set {
                this.agentidField = value;
                this.RaisePropertyChanged("agentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("articles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public articleVO[] articles {
            get {
                return this.articlesField;
            }
            set {
                this.articlesField = value;
                this.RaisePropertyChanged("articles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgtype {
            get {
                return this.msgtypeField;
            }
            set {
                this.msgtypeField = value;
                this.RaisePropertyChanged("msgtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string toparty {
            get {
                return this.topartyField;
            }
            set {
                this.topartyField = value;
                this.RaisePropertyChanged("toparty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string totag {
            get {
                return this.totagField;
            }
            set {
                this.totagField = value;
                this.RaisePropertyChanged("totag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string touser {
            get {
                return this.touserField;
            }
            set {
                this.touserField = value;
                this.RaisePropertyChanged("touser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class articleVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string picurlField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string picurl {
            get {
                return this.picurlField;
            }
            set {
                this.picurlField = value;
                this.RaisePropertyChanged("picurl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class textMessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentidField;
        
        private string contentField;
        
        private string msgtypeField;
        
        private string safeField;
        
        private string topartyField;
        
        private string totagField;
        
        private string touserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agentid {
            get {
                return this.agentidField;
            }
            set {
                this.agentidField = value;
                this.RaisePropertyChanged("agentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgtype {
            get {
                return this.msgtypeField;
            }
            set {
                this.msgtypeField = value;
                this.RaisePropertyChanged("msgtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string safe {
            get {
                return this.safeField;
            }
            set {
                this.safeField = value;
                this.RaisePropertyChanged("safe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string toparty {
            get {
                return this.topartyField;
            }
            set {
                this.topartyField = value;
                this.RaisePropertyChanged("toparty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string totag {
            get {
                return this.totagField;
            }
            set {
                this.totagField = value;
                this.RaisePropertyChanged("totag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string touser {
            get {
                return this.touserField;
            }
            set {
                this.touserField = value;
                this.RaisePropertyChanged("touser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageToAgent", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class sendMessageToAgent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Laboratory.ServiceReference1.qyhMessageVO qyhMessageVO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public sendMessageToAgent() {
        }
        
        public sendMessageToAgent(Laboratory.ServiceReference1.qyhMessageVO qyhMessageVO, string callSystem, string nonceStr, string timestamp, string signature) {
            this.qyhMessageVO = qyhMessageVO;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageToAgentResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class sendMessageToAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendMessageToAgentResponse() {
        }
        
        public sendMessageToAgentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserByUserIdOrCode", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserByUserIdOrCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getQyhUserByUserIdOrCode() {
        }
        
        public getQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            this.userId = userId;
            this.code = code;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserByUserIdOrCodeResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserByUserIdOrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getQyhUserByUserIdOrCodeResponse() {
        }
        
        public getQyhUserByUserIdOrCodeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhDept", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhDept {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getAllQyhDept() {
        }
        
        public getAllQyhDept(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhDeptResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhDeptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAllQyhDeptResponse() {
        }
        
        public getAllQyhDeptResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserListByDate", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserListByDate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getQyhUserListByDate() {
        }
        
        public getQyhUserListByDate(string startDate, string endDate, string callSystem, string nonceStr, string timestamp, string signature) {
            this.startDate = startDate;
            this.endDate = endDate;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserListByDateResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserListByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getQyhUserListByDateResponse() {
        }
        
        public getQyhUserListByDateResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhAgent", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhAgent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getAllQyhAgent() {
        }
        
        public getAllQyhAgent(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhAgentResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAllQyhAgentResponse() {
        }
        
        public getAllQyhAgentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccessToken", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAccessToken {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getAccessToken() {
        }
        
        public getAccessToken(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccessTokenResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAccessTokenResponse() {
        }
        
        public getAccessTokenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserId", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getQyhUserId() {
        }
        
        public getQyhUserId(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            this.userId = userId;
            this.code = code;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserIdResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getQyhUserIdResponse() {
        }
        
        public getQyhUserIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWeixinPageInit", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getWeixinPageInit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pageUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getWeixinPageInit() {
        }
        
        public getWeixinPageInit(string callSystem, string pageUrl, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.pageUrl = pageUrl;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWeixinPageInitResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getWeixinPageInitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getWeixinPageInitResponse() {
        }
        
        public getWeixinPageInitResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJsapiTicket", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getJsapiTicket {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getJsapiTicket() {
        }
        
        public getJsapiTicket(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJsapiTicketResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getJsapiTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getJsapiTicketResponse() {
        }
        
        public getJsapiTicketResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserIdByMobile", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getUserIdByMobile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mobile;
        
        public getUserIdByMobile() {
        }
        
        public getUserIdByMobile(string callSystem, string nonceStr, string timestamp, string signature, string mobile) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
            this.mobile = mobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserIdByMobileResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getUserIdByMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getUserIdByMobileResponse() {
        }
        
        public getUserIdByMobileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQyhWeixinUtilServiceChannel : Laboratory.ServiceReference1.IQyhWeixinUtilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QyhWeixinUtilServiceClient : System.ServiceModel.ClientBase<Laboratory.ServiceReference1.IQyhWeixinUtilService>, Laboratory.ServiceReference1.IQyhWeixinUtilService {
        
        public QyhWeixinUtilServiceClient() {
        }
        
        public QyhWeixinUtilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QyhWeixinUtilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QyhWeixinUtilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QyhWeixinUtilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCodeResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getLocalQyhUserByUserIdOrCode(Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode request) {
            return base.Channel.getLocalQyhUserByUserIdOrCode(request);
        }
        
        public string getLocalQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode inValue = new Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCodeResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getLocalQyhUserByUserIdOrCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCodeResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getLocalQyhUserByUserIdOrCodeAsync(Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode request) {
            return base.Channel.getLocalQyhUserByUserIdOrCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCodeResponse> getLocalQyhUserByUserIdOrCodeAsync(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode inValue = new Laboratory.ServiceReference1.getLocalQyhUserByUserIdOrCode();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getLocalQyhUserByUserIdOrCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.sendMessageToAgentResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.sendMessageToAgent(Laboratory.ServiceReference1.sendMessageToAgent request) {
            return base.Channel.sendMessageToAgent(request);
        }
        
        public string sendMessageToAgent(Laboratory.ServiceReference1.qyhMessageVO qyhMessageVO, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.sendMessageToAgent inValue = new Laboratory.ServiceReference1.sendMessageToAgent();
            inValue.qyhMessageVO = qyhMessageVO;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.sendMessageToAgentResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).sendMessageToAgent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.sendMessageToAgentResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.sendMessageToAgentAsync(Laboratory.ServiceReference1.sendMessageToAgent request) {
            return base.Channel.sendMessageToAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.sendMessageToAgentResponse> sendMessageToAgentAsync(Laboratory.ServiceReference1.qyhMessageVO qyhMessageVO, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.sendMessageToAgent inValue = new Laboratory.ServiceReference1.sendMessageToAgent();
            inValue.qyhMessageVO = qyhMessageVO;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).sendMessageToAgentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getQyhUserByUserIdOrCodeResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getQyhUserByUserIdOrCode(Laboratory.ServiceReference1.getQyhUserByUserIdOrCode request) {
            return base.Channel.getQyhUserByUserIdOrCode(request);
        }
        
        public string getQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getQyhUserByUserIdOrCode inValue = new Laboratory.ServiceReference1.getQyhUserByUserIdOrCode();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getQyhUserByUserIdOrCodeResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getQyhUserByUserIdOrCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserByUserIdOrCodeResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getQyhUserByUserIdOrCodeAsync(Laboratory.ServiceReference1.getQyhUserByUserIdOrCode request) {
            return base.Channel.getQyhUserByUserIdOrCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserByUserIdOrCodeResponse> getQyhUserByUserIdOrCodeAsync(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getQyhUserByUserIdOrCode inValue = new Laboratory.ServiceReference1.getQyhUserByUserIdOrCode();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getQyhUserByUserIdOrCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getAllQyhDeptResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getAllQyhDept(Laboratory.ServiceReference1.getAllQyhDept request) {
            return base.Channel.getAllQyhDept(request);
        }
        
        public string getAllQyhDept(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getAllQyhDept inValue = new Laboratory.ServiceReference1.getAllQyhDept();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getAllQyhDeptResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getAllQyhDept(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAllQyhDeptResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getAllQyhDeptAsync(Laboratory.ServiceReference1.getAllQyhDept request) {
            return base.Channel.getAllQyhDeptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAllQyhDeptResponse> getAllQyhDeptAsync(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getAllQyhDept inValue = new Laboratory.ServiceReference1.getAllQyhDept();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getAllQyhDeptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getQyhUserListByDateResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getQyhUserListByDate(Laboratory.ServiceReference1.getQyhUserListByDate request) {
            return base.Channel.getQyhUserListByDate(request);
        }
        
        public string getQyhUserListByDate(string startDate, string endDate, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getQyhUserListByDate inValue = new Laboratory.ServiceReference1.getQyhUserListByDate();
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getQyhUserListByDateResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getQyhUserListByDate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserListByDateResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getQyhUserListByDateAsync(Laboratory.ServiceReference1.getQyhUserListByDate request) {
            return base.Channel.getQyhUserListByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserListByDateResponse> getQyhUserListByDateAsync(string startDate, string endDate, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getQyhUserListByDate inValue = new Laboratory.ServiceReference1.getQyhUserListByDate();
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getQyhUserListByDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getAllQyhAgentResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getAllQyhAgent(Laboratory.ServiceReference1.getAllQyhAgent request) {
            return base.Channel.getAllQyhAgent(request);
        }
        
        public string getAllQyhAgent(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getAllQyhAgent inValue = new Laboratory.ServiceReference1.getAllQyhAgent();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getAllQyhAgentResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getAllQyhAgent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAllQyhAgentResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getAllQyhAgentAsync(Laboratory.ServiceReference1.getAllQyhAgent request) {
            return base.Channel.getAllQyhAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAllQyhAgentResponse> getAllQyhAgentAsync(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getAllQyhAgent inValue = new Laboratory.ServiceReference1.getAllQyhAgent();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getAllQyhAgentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getAccessTokenResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getAccessToken(Laboratory.ServiceReference1.getAccessToken request) {
            return base.Channel.getAccessToken(request);
        }
        
        public string getAccessToken(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getAccessToken inValue = new Laboratory.ServiceReference1.getAccessToken();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getAccessTokenResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getAccessToken(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAccessTokenResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getAccessTokenAsync(Laboratory.ServiceReference1.getAccessToken request) {
            return base.Channel.getAccessTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getAccessTokenResponse> getAccessTokenAsync(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getAccessToken inValue = new Laboratory.ServiceReference1.getAccessToken();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getAccessTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getQyhUserIdResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getQyhUserId(Laboratory.ServiceReference1.getQyhUserId request) {
            return base.Channel.getQyhUserId(request);
        }
        
        public string getQyhUserId(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getQyhUserId inValue = new Laboratory.ServiceReference1.getQyhUserId();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getQyhUserIdResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getQyhUserId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserIdResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getQyhUserIdAsync(Laboratory.ServiceReference1.getQyhUserId request) {
            return base.Channel.getQyhUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getQyhUserIdResponse> getQyhUserIdAsync(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getQyhUserId inValue = new Laboratory.ServiceReference1.getQyhUserId();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getQyhUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getWeixinPageInitResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getWeixinPageInit(Laboratory.ServiceReference1.getWeixinPageInit request) {
            return base.Channel.getWeixinPageInit(request);
        }
        
        public string getWeixinPageInit(string callSystem, string pageUrl, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getWeixinPageInit inValue = new Laboratory.ServiceReference1.getWeixinPageInit();
            inValue.callSystem = callSystem;
            inValue.pageUrl = pageUrl;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getWeixinPageInitResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getWeixinPageInit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getWeixinPageInitResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getWeixinPageInitAsync(Laboratory.ServiceReference1.getWeixinPageInit request) {
            return base.Channel.getWeixinPageInitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getWeixinPageInitResponse> getWeixinPageInitAsync(string callSystem, string pageUrl, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getWeixinPageInit inValue = new Laboratory.ServiceReference1.getWeixinPageInit();
            inValue.callSystem = callSystem;
            inValue.pageUrl = pageUrl;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getWeixinPageInitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getJsapiTicketResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getJsapiTicket(Laboratory.ServiceReference1.getJsapiTicket request) {
            return base.Channel.getJsapiTicket(request);
        }
        
        public string getJsapiTicket(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getJsapiTicket inValue = new Laboratory.ServiceReference1.getJsapiTicket();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            Laboratory.ServiceReference1.getJsapiTicketResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getJsapiTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getJsapiTicketResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getJsapiTicketAsync(Laboratory.ServiceReference1.getJsapiTicket request) {
            return base.Channel.getJsapiTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getJsapiTicketResponse> getJsapiTicketAsync(string callSystem, string nonceStr, string timestamp, string signature) {
            Laboratory.ServiceReference1.getJsapiTicket inValue = new Laboratory.ServiceReference1.getJsapiTicket();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getJsapiTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratory.ServiceReference1.getUserIdByMobileResponse Laboratory.ServiceReference1.IQyhWeixinUtilService.getUserIdByMobile(Laboratory.ServiceReference1.getUserIdByMobile request) {
            return base.Channel.getUserIdByMobile(request);
        }
        
        public string getUserIdByMobile(string callSystem, string nonceStr, string timestamp, string signature, string mobile) {
            Laboratory.ServiceReference1.getUserIdByMobile inValue = new Laboratory.ServiceReference1.getUserIdByMobile();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            inValue.mobile = mobile;
            Laboratory.ServiceReference1.getUserIdByMobileResponse retVal = ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getUserIdByMobile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratory.ServiceReference1.getUserIdByMobileResponse> Laboratory.ServiceReference1.IQyhWeixinUtilService.getUserIdByMobileAsync(Laboratory.ServiceReference1.getUserIdByMobile request) {
            return base.Channel.getUserIdByMobileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratory.ServiceReference1.getUserIdByMobileResponse> getUserIdByMobileAsync(string callSystem, string nonceStr, string timestamp, string signature, string mobile) {
            Laboratory.ServiceReference1.getUserIdByMobile inValue = new Laboratory.ServiceReference1.getUserIdByMobile();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            inValue.mobile = mobile;
            return ((Laboratory.ServiceReference1.IQyhWeixinUtilService)(this)).getUserIdByMobileAsync(inValue);
        }
    }
}
