//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab.impala.OpenWeChatService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://qyh.webService.est.yonyou.com/", ConfigurationName="OpenWeChatService.IQyhWeixinUtilService")]
    public interface IQyhWeixinUtilService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCodeResponse getLocalQyhUserByUserIdOrCode(lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCode request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.sendMessageToAgentResponse sendMessageToAgent(lab.impala.OpenWeChatService.sendMessageToAgent request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getQyhUserByUserIdOrCodeResponse getQyhUserByUserIdOrCode(lab.impala.OpenWeChatService.getQyhUserByUserIdOrCode request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getAllQyhDeptResponse getAllQyhDept(lab.impala.OpenWeChatService.getAllQyhDept request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getQyhUserListByDateResponse getQyhUserListByDate(lab.impala.OpenWeChatService.getQyhUserListByDate request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getAllQyhAgentResponse getAllQyhAgent(lab.impala.OpenWeChatService.getAllQyhAgent request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getAccessTokenResponse getAccessToken(lab.impala.OpenWeChatService.getAccessToken request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getQyhUserIdResponse getQyhUserId(lab.impala.OpenWeChatService.getQyhUserId request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getWeixinPageInitResponse getWeixinPageInit(lab.impala.OpenWeChatService.getWeixinPageInit request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getJsapiTicketResponse getJsapiTicket(lab.impala.OpenWeChatService.getJsapiTicket request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lab.impala.OpenWeChatService.getUserIdByMobileResponse getUserIdByMobile(lab.impala.OpenWeChatService.getUserIdByMobile request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalQyhUserByUserIdOrCode", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getLocalQyhUserByUserIdOrCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getLocalQyhUserByUserIdOrCode() {
        }
        
        public getLocalQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            this.userId = userId;
            this.code = code;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalQyhUserByUserIdOrCodeResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getLocalQyhUserByUserIdOrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getLocalQyhUserByUserIdOrCodeResponse() {
        }
        
        public getLocalQyhUserByUserIdOrCodeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class qyhMessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgtypeField;
        
        private newsMessageVO newsVOField;
        
        private textMessageVO textVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string msgtype {
            get {
                return this.msgtypeField;
            }
            set {
                this.msgtypeField = value;
                this.RaisePropertyChanged("msgtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public newsMessageVO newsVO {
            get {
                return this.newsVOField;
            }
            set {
                this.newsVOField = value;
                this.RaisePropertyChanged("newsVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public textMessageVO textVO {
            get {
                return this.textVOField;
            }
            set {
                this.textVOField = value;
                this.RaisePropertyChanged("textVO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class newsMessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentidField;
        
        private articleVO[] articlesField;
        
        private string msgtypeField;
        
        private string topartyField;
        
        private string totagField;
        
        private string touserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agentid {
            get {
                return this.agentidField;
            }
            set {
                this.agentidField = value;
                this.RaisePropertyChanged("agentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("articles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public articleVO[] articles {
            get {
                return this.articlesField;
            }
            set {
                this.articlesField = value;
                this.RaisePropertyChanged("articles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgtype {
            get {
                return this.msgtypeField;
            }
            set {
                this.msgtypeField = value;
                this.RaisePropertyChanged("msgtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string toparty {
            get {
                return this.topartyField;
            }
            set {
                this.topartyField = value;
                this.RaisePropertyChanged("toparty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string totag {
            get {
                return this.totagField;
            }
            set {
                this.totagField = value;
                this.RaisePropertyChanged("totag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string touser {
            get {
                return this.touserField;
            }
            set {
                this.touserField = value;
                this.RaisePropertyChanged("touser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class articleVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string picurlField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string picurl {
            get {
                return this.picurlField;
            }
            set {
                this.picurlField = value;
                this.RaisePropertyChanged("picurl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qyh.webService.est.yonyou.com/")]
    public partial class textMessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentidField;
        
        private string contentField;
        
        private string msgtypeField;
        
        private string safeField;
        
        private string topartyField;
        
        private string totagField;
        
        private string touserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agentid {
            get {
                return this.agentidField;
            }
            set {
                this.agentidField = value;
                this.RaisePropertyChanged("agentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgtype {
            get {
                return this.msgtypeField;
            }
            set {
                this.msgtypeField = value;
                this.RaisePropertyChanged("msgtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string safe {
            get {
                return this.safeField;
            }
            set {
                this.safeField = value;
                this.RaisePropertyChanged("safe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string toparty {
            get {
                return this.topartyField;
            }
            set {
                this.topartyField = value;
                this.RaisePropertyChanged("toparty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string totag {
            get {
                return this.totagField;
            }
            set {
                this.totagField = value;
                this.RaisePropertyChanged("totag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string touser {
            get {
                return this.touserField;
            }
            set {
                this.touserField = value;
                this.RaisePropertyChanged("touser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageToAgent", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class sendMessageToAgent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public lab.impala.OpenWeChatService.qyhMessageVO qyhMessageVO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public sendMessageToAgent() {
        }
        
        public sendMessageToAgent(lab.impala.OpenWeChatService.qyhMessageVO qyhMessageVO, string callSystem, string nonceStr, string timestamp, string signature) {
            this.qyhMessageVO = qyhMessageVO;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageToAgentResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class sendMessageToAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendMessageToAgentResponse() {
        }
        
        public sendMessageToAgentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserByUserIdOrCode", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserByUserIdOrCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getQyhUserByUserIdOrCode() {
        }
        
        public getQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            this.userId = userId;
            this.code = code;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserByUserIdOrCodeResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserByUserIdOrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getQyhUserByUserIdOrCodeResponse() {
        }
        
        public getQyhUserByUserIdOrCodeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhDept", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhDept {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getAllQyhDept() {
        }
        
        public getAllQyhDept(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhDeptResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhDeptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAllQyhDeptResponse() {
        }
        
        public getAllQyhDeptResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserListByDate", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserListByDate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getQyhUserListByDate() {
        }
        
        public getQyhUserListByDate(string startDate, string endDate, string callSystem, string nonceStr, string timestamp, string signature) {
            this.startDate = startDate;
            this.endDate = endDate;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserListByDateResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserListByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getQyhUserListByDateResponse() {
        }
        
        public getQyhUserListByDateResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhAgent", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhAgent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getAllQyhAgent() {
        }
        
        public getAllQyhAgent(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQyhAgentResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAllQyhAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAllQyhAgentResponse() {
        }
        
        public getAllQyhAgentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccessToken", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAccessToken {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getAccessToken() {
        }
        
        public getAccessToken(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccessTokenResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAccessTokenResponse() {
        }
        
        public getAccessTokenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserId", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getQyhUserId() {
        }
        
        public getQyhUserId(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            this.userId = userId;
            this.code = code;
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQyhUserIdResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getQyhUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getQyhUserIdResponse() {
        }
        
        public getQyhUserIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWeixinPageInit", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getWeixinPageInit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pageUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getWeixinPageInit() {
        }
        
        public getWeixinPageInit(string callSystem, string pageUrl, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.pageUrl = pageUrl;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWeixinPageInitResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getWeixinPageInitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getWeixinPageInitResponse() {
        }
        
        public getWeixinPageInitResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJsapiTicket", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getJsapiTicket {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        public getJsapiTicket() {
        }
        
        public getJsapiTicket(string callSystem, string nonceStr, string timestamp, string signature) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJsapiTicketResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getJsapiTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getJsapiTicketResponse() {
        }
        
        public getJsapiTicketResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserIdByMobile", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getUserIdByMobile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonceStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mobile;
        
        public getUserIdByMobile() {
        }
        
        public getUserIdByMobile(string callSystem, string nonceStr, string timestamp, string signature, string mobile) {
            this.callSystem = callSystem;
            this.nonceStr = nonceStr;
            this.timestamp = timestamp;
            this.signature = signature;
            this.mobile = mobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserIdByMobileResponse", WrapperNamespace="http://qyh.webService.est.yonyou.com/", IsWrapped=true)]
    public partial class getUserIdByMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qyh.webService.est.yonyou.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getUserIdByMobileResponse() {
        }
        
        public getUserIdByMobileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQyhWeixinUtilServiceChannel : lab.impala.OpenWeChatService.IQyhWeixinUtilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QyhWeixinUtilServiceClient : System.ServiceModel.ClientBase<lab.impala.OpenWeChatService.IQyhWeixinUtilService>, lab.impala.OpenWeChatService.IQyhWeixinUtilService {
        
        public QyhWeixinUtilServiceClient() {
        }
        
        public QyhWeixinUtilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QyhWeixinUtilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QyhWeixinUtilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QyhWeixinUtilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCodeResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getLocalQyhUserByUserIdOrCode(lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCode request) {
            return base.Channel.getLocalQyhUserByUserIdOrCode(request);
        }
        
        public string getLocalQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCode inValue = new lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCode();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getLocalQyhUserByUserIdOrCodeResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getLocalQyhUserByUserIdOrCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.sendMessageToAgentResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.sendMessageToAgent(lab.impala.OpenWeChatService.sendMessageToAgent request) {
            return base.Channel.sendMessageToAgent(request);
        }
        
        public string sendMessageToAgent(lab.impala.OpenWeChatService.qyhMessageVO qyhMessageVO, string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.sendMessageToAgent inValue = new lab.impala.OpenWeChatService.sendMessageToAgent();
            inValue.qyhMessageVO = qyhMessageVO;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.sendMessageToAgentResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).sendMessageToAgent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getQyhUserByUserIdOrCodeResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getQyhUserByUserIdOrCode(lab.impala.OpenWeChatService.getQyhUserByUserIdOrCode request) {
            return base.Channel.getQyhUserByUserIdOrCode(request);
        }
        
        public string getQyhUserByUserIdOrCode(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getQyhUserByUserIdOrCode inValue = new lab.impala.OpenWeChatService.getQyhUserByUserIdOrCode();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getQyhUserByUserIdOrCodeResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getQyhUserByUserIdOrCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getAllQyhDeptResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getAllQyhDept(lab.impala.OpenWeChatService.getAllQyhDept request) {
            return base.Channel.getAllQyhDept(request);
        }
        
        public string getAllQyhDept(string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getAllQyhDept inValue = new lab.impala.OpenWeChatService.getAllQyhDept();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getAllQyhDeptResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getAllQyhDept(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getQyhUserListByDateResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getQyhUserListByDate(lab.impala.OpenWeChatService.getQyhUserListByDate request) {
            return base.Channel.getQyhUserListByDate(request);
        }
        
        public string getQyhUserListByDate(string startDate, string endDate, string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getQyhUserListByDate inValue = new lab.impala.OpenWeChatService.getQyhUserListByDate();
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getQyhUserListByDateResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getQyhUserListByDate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getAllQyhAgentResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getAllQyhAgent(lab.impala.OpenWeChatService.getAllQyhAgent request) {
            return base.Channel.getAllQyhAgent(request);
        }
        
        public string getAllQyhAgent(string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getAllQyhAgent inValue = new lab.impala.OpenWeChatService.getAllQyhAgent();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getAllQyhAgentResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getAllQyhAgent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getAccessTokenResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getAccessToken(lab.impala.OpenWeChatService.getAccessToken request) {
            return base.Channel.getAccessToken(request);
        }
        
        public string getAccessToken(string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getAccessToken inValue = new lab.impala.OpenWeChatService.getAccessToken();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getAccessTokenResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getAccessToken(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getQyhUserIdResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getQyhUserId(lab.impala.OpenWeChatService.getQyhUserId request) {
            return base.Channel.getQyhUserId(request);
        }
        
        public string getQyhUserId(string userId, string code, string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getQyhUserId inValue = new lab.impala.OpenWeChatService.getQyhUserId();
            inValue.userId = userId;
            inValue.code = code;
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getQyhUserIdResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getQyhUserId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getWeixinPageInitResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getWeixinPageInit(lab.impala.OpenWeChatService.getWeixinPageInit request) {
            return base.Channel.getWeixinPageInit(request);
        }
        
        public string getWeixinPageInit(string callSystem, string pageUrl, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getWeixinPageInit inValue = new lab.impala.OpenWeChatService.getWeixinPageInit();
            inValue.callSystem = callSystem;
            inValue.pageUrl = pageUrl;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getWeixinPageInitResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getWeixinPageInit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getJsapiTicketResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getJsapiTicket(lab.impala.OpenWeChatService.getJsapiTicket request) {
            return base.Channel.getJsapiTicket(request);
        }
        
        public string getJsapiTicket(string callSystem, string nonceStr, string timestamp, string signature) {
            lab.impala.OpenWeChatService.getJsapiTicket inValue = new lab.impala.OpenWeChatService.getJsapiTicket();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            lab.impala.OpenWeChatService.getJsapiTicketResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getJsapiTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab.impala.OpenWeChatService.getUserIdByMobileResponse lab.impala.OpenWeChatService.IQyhWeixinUtilService.getUserIdByMobile(lab.impala.OpenWeChatService.getUserIdByMobile request) {
            return base.Channel.getUserIdByMobile(request);
        }
        
        public string getUserIdByMobile(string callSystem, string nonceStr, string timestamp, string signature, string mobile) {
            lab.impala.OpenWeChatService.getUserIdByMobile inValue = new lab.impala.OpenWeChatService.getUserIdByMobile();
            inValue.callSystem = callSystem;
            inValue.nonceStr = nonceStr;
            inValue.timestamp = timestamp;
            inValue.signature = signature;
            inValue.mobile = mobile;
            lab.impala.OpenWeChatService.getUserIdByMobileResponse retVal = ((lab.impala.OpenWeChatService.IQyhWeixinUtilService)(this)).getUserIdByMobile(inValue);
            return retVal.@return;
        }
    }
}
